# Generated by Django 5.2 on 2025-05-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_gym_gymmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_icon',
            field=models.ImageField(blank=True, null=True, upload_to='gym_images/'),
        ),
    ]
