# Generated by Django 5.2 on 2025-05-05 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_profile_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='profile',
            new_name='profile_icon',
        ),
    ]
