# Generated by Django 5.2 on 2025-05-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_profile_gym_profile_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='A', max_length=2),
        ),
    ]
