# Generated by Django 5.2 on 2025-05-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_gym_is_verified_customuser_status_gym_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='gym',
            name='per_session_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
