# Generated by Django 5.2 on 2025-05-10 17:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_gym_currency_gym_per_session_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='gym_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
