# Generated by Django 5.2 on 2025-05-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_gym_gym_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='premium_type',
            field=models.CharField(choices=[('B', 'Basic'), ('V', 'VIP')], default='B', max_length=2),
        ),
    ]
