# Generated by Django 5.2 on 2025-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_gym_premium_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('G', 'Gym')], default='A', max_length=2),
        ),
    ]
