# Generated by Django 5.2 on 2025-05-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_type',
            field=models.CharField(choices=[('M', 'Mobile Number'), ('E', 'Email')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('U', 'User'), ('G', 'Gym')], default='U', max_length=2),
        ),
    ]
