# Generated by Django 5.2 on 2025-05-16 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 13, 3, 27, 559601, tzinfo=datetime.timezone.utc)),
        ),
    ]
