# Generated by Django 5.2 on 2025-05-16 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_icon',
            field=models.ImageField(blank=True, default='/default/profile.png', null=True, upload_to='gym_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 16, 29, 55, 54979, tzinfo=datetime.timezone.utc)),
        ),
    ]
