# Generated by Django 5.2 on 2025-05-16 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_customuser_profile_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='new_to_gym',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 17, 39, 20, 529446, tzinfo=datetime.timezone.utc)),
        ),
    ]
