# Generated by Django 5.2 on 2025-05-29 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_height_customuser_new_to_gym_and_more'),
        ('lookups', '0002_gymfeature_alter_exercisename_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='feature',
            field=models.ManyToManyField(blank=True, null=True, to='lookups.gymfeature'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='profile_icon',
            field=models.ImageField(blank=True, default='/default/gym_profile.png', null=True, upload_to='gym_images/'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 29, 16, 12, 12, 82615, tzinfo=datetime.timezone.utc)),
        ),
    ]
