# Generated by Django 5.2 on 2025-05-31 03:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_gym_feature_alter_gym_profile_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 3, 54, 35, 617343, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='GymTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MF', 'Monday - Friday'), ('MS', 'Monday - Saturday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=3)),
                ('morning_start', models.TimeField(blank=True, null=True)),
                ('morning_end', models.TimeField(blank=True, null=True)),
                ('evening_start', models.TimeField(blank=True, null=True)),
                ('evening_end', models.TimeField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='A', max_length=2)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gym')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
