# Generated by Django 5.2 on 2025-05-31 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_userotp_expire_on_gymequipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymequipment',
            name='icon',
            field=models.ImageField(blank=True, default='/default/gym_equipment.png', null=True, upload_to='gym_images/equipment'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 31, 16, 43, 43, 869050, tzinfo=datetime.timezone.utc)),
        ),
    ]
