# Generated by Django 5.2 on 2025-06-01 10:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_userotp_expire_on_gymfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 10, 56, 51, 8394, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='UserSelectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='A', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
