# Generated by Django 5.2 on 2025-06-01 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_userotp_expire_on_userselectlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 1, 17, 15, 7, 594184, tzinfo=datetime.timezone.utc)),
        ),
    ]
