# Generated by Django 5.2 on 2025-06-07 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_gym_verified_at_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselectlocation',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userselectlocation',
            name='display_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 8, 53, 7, 458514, tzinfo=datetime.timezone.utc)),
        ),
    ]
