# Generated by Django 5.2 on 2025-06-07 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_gym_latitude_alter_gym_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 7, 13, 25, 5, 236911, tzinfo=datetime.timezone.utc)),
        ),
    ]
