# Generated by Django 5.2 on 2025-08-03 09:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_customuser_zip_code_gym_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 9, 15, 19, 861991, tzinfo=datetime.timezone.utc)),
        ),
    ]
