# Generated by Django 5.2 on 2025-08-03 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_gym_verified_by_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 9, 20, 56, 441432, tzinfo=datetime.timezone.utc)),
        ),
    ]
