# Generated by Django 5.2 on 2025-08-30 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 30, 18, 40, 32, 921594, tzinfo=datetime.timezone.utc)),
        ),
    ]
