# Generated by Django 5.2 on 2026-01-23 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 12, 59, 23, 370859, tzinfo=datetime.timezone.utc)),
        ),
    ]
