# Generated by Django 5.2 on 2026-01-26 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 17, 19, 36, 341515, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userselectlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='userselectlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=50, null=True),
        ),
    ]
