# Generated by Django 5.2 on 2026-01-26 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_userotp_expire_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 17, 22, 13, 535614, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userselectlocation',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userselectlocation',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
