# Generated by Django 5.2 on 2026-02-01 19:03

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_userotp_expire_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmedia',
            name='media_new',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 19, 6, 14, 457061, tzinfo=datetime.timezone.utc)),
        ),
    ]
