# Generated by Django 5.2 on 2026-02-01 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_gymmedia_media_new_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 19, 16, 9, 620135, tzinfo=datetime.timezone.utc)),
        ),
    ]
