# Generated by Django 5.2 on 2026-02-02 07:41

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmedia',
            name='media_new',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_icon',
            field=cloudinary.models.CloudinaryField(blank=True, default='/default/profile.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='profile_icon',
            field=cloudinary.models.CloudinaryField(blank=True, default='/default/gym_profile.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gymequipment',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, default='/default/gym_equipment.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gymmedia',
            name='media',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 2, 7, 46, 25, 558044, tzinfo=datetime.timezone.utc)),
        ),
    ]
