# Generated by Django 5.2 on 2026-02-10 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_customuser_profile_icon_alter_gym_profile_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 13, 58, 45, 504349, tzinfo=datetime.timezone.utc)),
        ),
    ]
