# Generated by Django 5.2 on 2026-02-14 14:51

import accounts.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_customuser_address_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=accounts.models.generate_referral_code, max_length=12),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 14, 56, 56, 661481, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('reward_points', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('user_status', models.CharField(choices=[('P', 'Pending'), ('C', 'Created')], default='P', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
