# Generated by Django 5.2 on 2026-02-14 14:56

import accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_customuser_referral_code_alter_userotp_expire_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=accounts.models.generate_referral_code, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 15, 1, 11, 382187, tzinfo=datetime.timezone.utc)),
        ),
    ]
