# Generated by Django 5.2 on 2026-02-16 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_userotp_expire_on_freesessionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 16, 13, 26, 22, 102720, tzinfo=datetime.timezone.utc)),
        ),
    ]
