# Generated by Django 5.2 on 2026-02-22 09:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gym',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 22, 9, 23, 33, 607651, tzinfo=datetime.timezone.utc)),
        ),
    ]
