# Generated by Django 5.2 on 2026-03-12 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_gym_created_by_alter_gym_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('G', 'Gym'), ('E', 'Executive')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 12, 17, 47, 49, 533834, tzinfo=datetime.timezone.utc)),
        ),
    ]
