# Generated by Django 5.2 on 2026-03-27 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_customuser_user_type_alter_userotp_expire_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_trigger',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_trigger',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 7, 2, 23, 386734, tzinfo=datetime.timezone.utc)),
        ),
    ]
