# Generated by Django 5.2 on 2026-04-14 15:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_alter_userotp_expire_on_accountdeleterequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountdeleterequest',
            options={'ordering': ['-requested_on']},
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 14, 15, 28, 2, 718566, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=11)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
