# Generated by Django 5.2 on 2026-04-30 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_accountdeleterequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fire_base_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gym',
            name='premium_type',
            field=models.CharField(choices=[('B', 'Basic'), ('V', 'VIP'), ('E', 'Elite')], default='B', max_length=2),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 30, 13, 39, 45, 157399, tzinfo=datetime.timezone.utc)),
        ),
    ]
