# Generated by Django 5.2 on 2025-05-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('icon', models.ImageField(blank=True, default='/default/feature_icon.png', null=True, upload_to='lookup/gym_feature/')),
                ('details', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=2)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AlterModelOptions(
            name='exercisename',
            options={'ordering': ['position']},
        ),
    ]
