# Generated by Django 5.2 on 2025-05-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0002_gymfeature_alter_exercisename_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymfeature',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
