# Generated by Django 5.2 on 2026-02-02 07:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0003_alter_gymfeature_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymfeature',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, default='/default/feature_icon.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
