# Generated by Django 5.2 on 2026-02-02 17:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0004_alter_gymfeature_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymfeature',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
