# Generated by Django 5.2 on 2026-09-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0005_alter_gymfeature_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('membership', 'Membership Support'), ('payment', 'Payment Issue'), ('partner', 'Partner With Us'), ('technical', 'Technical Support')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'In Progress'), ('R', 'Resolved'), ('S', 'Spam')], default='N', max_length=2)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(max_length=120)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('C', 'Contacted'), ('Q', 'Qualified'), ('O', 'Onboarded'), ('X', 'Not a fit')], default='N', max_length=2)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
