# Generated by Django 5.2 on 2025-05-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
