# Generated by Django 5.2 on 2025-05-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscriptionhistory_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='premium_type',
            field=models.CharField(choices=[('B', 'Basic'), ('V', 'VIP')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('E', 'Error'), ('S', 'Success')], default='P', max_length=2),
        ),
    ]
