# Generated by Django 5.2 on 2025-05-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_premium_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='premium_type',
            new_name='premim_type',
        ),
    ]
