# Generated by Django 5.2 on 2025-05-17 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_rename_premium_type_subscriptionplan_premim_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersubscriptionhistory',
            old_name='price',
            new_name='per_session_price',
        ),
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='subscription_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='total_session_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='usersubscriptionhistory',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='usersubscriptionhistory',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='usersubscriptionhistory',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
