# Generated by Django 5.2 on 2025-07-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_rename_price_usersubscriptionhistory_per_session_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetails',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_details', to='subscriptions.subscriptionplan'),
        ),
    ]
