# Generated by Django 5.2 on 2025-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_plandetails_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptionhistory',
            name='order_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
