# Generated by Django 5.2 on 2025-08-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_usersubscriptionhistory_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='razorpay_order_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscriptionhistory',
            name='order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
