# Generated by Django 5.2 on 2026-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_usersubscriptionhistory_error_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plandetails',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
