# Generated by Django 5.2 on 2026-01-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_alter_plandetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='coupon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='coupon_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='coupon_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
