# Generated by Django 5.2 on 2026-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_usersubscriptionhistory_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='price_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
