# Generated by Django 5.2 on 2026-07-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_dicountcoupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='premim_type',
            field=models.CharField(choices=[('B', 'Basic'), ('V', 'VIP'), ('E', 'Elite')], default='B', max_length=2),
        ),
        migrations.AddIndex(
            model_name='plandetails',
            index=models.Index(fields=['plan', 'status'], name='subscriptio_plan_id_1a9193_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionplan',
            index=models.Index(fields=['status', 'premim_type'], name='subscriptio_status_6d644a_idx'),
        ),
    ]
