# Generated by Django 5.2 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_subscriptionplan_is_popular'),
    ]

    operations = [
        # The webhook, the list view and the mobile app have all been using
        # 'F' / 'Failed' for a failed payment, but the model choices still
        # said ('E', 'Error') — so get_payment_status_display() returned a
        # bare 'F' and the admin flagged those rows as invalid. Choices-only
        # change, no schema/data migration needed (there are 'F' rows and no
        # 'E' rows).
        migrations.AlterField(
            model_name='usersubscriptionhistory',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('F', 'Failed'), ('S', 'Success')], default='P', max_length=2),
        ),
    ]
