# Generated by Django 5.2 on 2026-09-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0016_alter_usersubscriptionhistory_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='fitpoints_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='usersubscriptionhistory',
            name='fitpoints_redeemed',
            field=models.IntegerField(default=0),
        ),
    ]
