# Generated by Django 5.2 on 2025-05-11 04:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_gym_gym_id'),
        ('lookups', '0001_initial'),
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutschedule',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutschedule',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='workoutschedule',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='workoutschedule',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='workoutschedule',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='workoutschedule',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='workoutschedule',
            name='status',
        ),
        migrations.RemoveField(
            model_name='workoutschedule',
            name='weight',
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='scheduled_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='workout_type',
            field=models.ManyToManyField(related_name='users', to='lookups.workouttype'),
        ),
        migrations.CreateModel(
            name='GymAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_access_id', models.UUIDField(default=uuid.uuid4)),
                ('date', models.DateField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='gym_access',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.gymaccesslog'),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('D', 'Deleted')], default='A', max_length=2)),
                ('workout_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workoutschedule')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutLog',
        ),
    ]
