# Generated by Django 5.2 on 2025-05-11 04:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workoutschedule_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutschedule',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
