# Generated by Django 5.2 on 2025-05-11 05:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workoutschedule_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
