# Generated by Django 5.2 on 2025-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_workoutexercise_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='body_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='burned_calories',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutschedule',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
