# Generated by Django 5.2 on 2025-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workoutschedule_body_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymaccesslog',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
