# Generated by Django 5.2 on 2025-05-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_gymaccesslog_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymaccesslog',
            name='date',
        ),
        migrations.AddField(
            model_name='gymaccesslog',
            name='access_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
