# Generated by Django 5.2 on 2025-05-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookups', '0001_initial'),
        ('workouts', '0007_remove_gymaccesslog_date_gymaccesslog_access_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutschedule',
            name='workout_type',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='lookups.workouttype'),
        ),
    ]
