# Generated by Django 5.2 on 2026-01-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_workoutschedule_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutschedule',
            name='reminder',
            field=models.BooleanField(default=True),
        ),
    ]
