# Generated by Django 5.2 on 2026-03-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_workoutschedule_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymaccesslog',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gymaccesslog',
            name='settled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gymaccesslog',
            name='settled_status',
            field=models.CharField(choices=[('P', 'Pending'), ('IP', 'In Progress'), ('PR', 'Processed')], default='P', max_length=2),
        ),
    ]
