# Generated by Django 5.2 on 2026-03-12 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_alter_customuser_user_type_alter_userotp_expire_on'),
        ('workouts', '0010_gymaccesslog_amount_gymaccesslog_settled_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymaccesslog',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.gymreview'),
        ),
    ]
